# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -IDesert/Common/Source -IDesert/Common/Source/Common -IThirdParty/spdlog/include -IThirdParty/GLFW/include -IThirdParty/yaml-cpp/include -IThirdParty/optick/src -IThirdParty/glm -IThirdParty/reflect-cpp/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
ALL_LDFLAGS += $(LDFLAGS) -L/opt/homebrew/lib -arch arm64 -mmacosx-version-min=14.0
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = build/Bin/Debug
TARGET = $(TARGETDIR)/libCommon.a
OBJDIR = build/Intermediates/Debug/Debug/Common
DEFINES += -DYAML_CPP_STATIC_DEFINE -DUSE_OPTICK=1 -DOPTICK_ENABLE_GPU=0 -DOPTICK_ENABLE_TRACING=0 -DDESERT_CONFIG_DEBUG -DDESERT_PLATFORM_MACOS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -arch arm64 -g -w -mmacosx-version-min=14.0
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -arch arm64 -g -w -std=c++20 -mmacosx-version-min=14.0
LIBS += build/Bin/Debug/libyaml-cpp.a build/Bin/Debug/libOptick.a
LDDEPS += build/Bin/Debug/libyaml-cpp.a build/Bin/Debug/libOptick.a

else ifeq ($(config),release)
TARGETDIR = build/Bin/Release
TARGET = $(TARGETDIR)/libCommon.a
OBJDIR = build/Intermediates/Release/Release/Common
DEFINES += -DNDEBUG -DYAML_CPP_STATIC_DEFINE -DUSE_OPTICK=1 -DOPTICK_ENABLE_GPU=0 -DOPTICK_ENABLE_TRACING=0 -DDESERT_CONFIG_RELEASE -DDESERT_PLATFORM_MACOS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -arch arm64 -O2 -w -mmacosx-version-min=14.0
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -arch arm64 -O2 -w -std=c++20 -mmacosx-version-min=14.0
LIBS += build/Bin/Release/libyaml-cpp.a build/Bin/Release/libOptick.a
LDDEPS += build/Bin/Release/libyaml-cpp.a build/Bin/Release/libOptick.a

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/CameraCapture.o
GENERATED += $(OBJDIR)/Core.o
GENERATED += $(OBJDIR)/FileSystem.o
GENERATED += $(OBJDIR)/HandlePool.o
GENERATED += $(OBJDIR)/Interpolate.o
GENERATED += $(OBJDIR)/JobSystem.o
GENERATED += $(OBJDIR)/Layer.o
GENERATED += $(OBJDIR)/LayerStack.o
GENERATED += $(OBJDIR)/MacOSCamera.o
GENERATED += $(OBJDIR)/MacOSFileSystem.o
GENERATED += $(OBJDIR)/Notifier.o
GENERATED += $(OBJDIR)/PakFile.o
GENERATED += $(OBJDIR)/Profiler.o
GENERATED += $(OBJDIR)/Serialization.o
GENERATED += $(OBJDIR)/SpaceTransformer.o
GENERATED += $(OBJDIR)/String.o
GENERATED += $(OBJDIR)/Timestep.o
GENERATED += $(OBJDIR)/UUID.o
GENERATED += $(OBJDIR)/VFS.o
GENERATED += $(OBJDIR)/Version.o
OBJECTS += $(OBJDIR)/CameraCapture.o
OBJECTS += $(OBJDIR)/Core.o
OBJECTS += $(OBJDIR)/FileSystem.o
OBJECTS += $(OBJDIR)/HandlePool.o
OBJECTS += $(OBJDIR)/Interpolate.o
OBJECTS += $(OBJDIR)/JobSystem.o
OBJECTS += $(OBJDIR)/Layer.o
OBJECTS += $(OBJDIR)/LayerStack.o
OBJECTS += $(OBJDIR)/MacOSCamera.o
OBJECTS += $(OBJDIR)/MacOSFileSystem.o
OBJECTS += $(OBJDIR)/Notifier.o
OBJECTS += $(OBJDIR)/PakFile.o
OBJECTS += $(OBJDIR)/Profiler.o
OBJECTS += $(OBJDIR)/Serialization.o
OBJECTS += $(OBJDIR)/SpaceTransformer.o
OBJECTS += $(OBJDIR)/String.o
OBJECTS += $(OBJDIR)/Timestep.o
OBJECTS += $(OBJDIR)/UUID.o
OBJECTS += $(OBJDIR)/VFS.o
OBJECTS += $(OBJDIR)/Version.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking Common
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning Common
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/Core.o: Desert/Common/Source/Common/Core/Core.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/HandlePool.o: Desert/Common/Source/Common/Core/HandlePool.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/JobSystem.o: Desert/Common/Source/Common/Core/JobSystem.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Layer.o: Desert/Common/Source/Common/Core/Layer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LayerStack.o: Desert/Common/Source/Common/Core/LayerStack.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Interpolate.o: Desert/Common/Source/Common/Core/Math/Interpolate.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SpaceTransformer.o: Desert/Common/Source/Common/Core/Math/SpaceTransformer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Notifier.o: Desert/Common/Source/Common/Core/Notifier.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Profiler.o: Desert/Common/Source/Common/Core/Profiler.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Serialization.o: Desert/Common/Source/Common/Core/Serialization/Serialization.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Timestep.o: Desert/Common/Source/Common/Core/Timestep.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UUID.o: Desert/Common/Source/Common/Core/UUID.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Version.o: Desert/Common/Source/Common/Core/Version.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MacOSCamera.o: Desert/Common/Source/Common/Platform/MacOS/MacOSCamera.mm
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MacOSFileSystem.o: Desert/Common/Source/Common/Platform/MacOS/MacOSFileSystem.mm
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CameraCapture.o: Desert/Common/Source/Common/Utilities/CameraCapture.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FileSystem.o: Desert/Common/Source/Common/Utilities/FileSystem.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PakFile.o: Desert/Common/Source/Common/Utilities/PakFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/String.o: Desert/Common/Source/Common/Utilities/String.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VFS.o: Desert/Common/Source/Common/Utilities/VFS.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif