# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
PCH = Desert/Desert/Source/pch.hpp
PCH_PLACEHOLDER = $(OBJDIR)/$(notdir $(PCH))
GCH = $(PCH_PLACEHOLDER).gch
INCLUDES += -IDesert/Desert/Source -IDesert/Common/Source -IThirdParty/pl_mpeg/include -IThirdParty/spdlog/include -IThirdParty/GLFW/include -IThirdParty/yaml-cpp/include -IThirdParty/optick/src -IThirdParty/glm -IThirdParty/lua -IThirdParty/stb/ImGui -IThirdParty/meshoptimizer/src -IThirdParty/JoltPhysics -IThirdParty/reflect-cpp/include -I/opt/homebrew/include/spirv_cross -IThirdParty/VulkanAllocator -I/opt/homebrew/include/shaderc -IThirdParty/sol2/include -IThirdParty -I/opt/homebrew/include -IThirdParty/entt/include -IThirdParty/stb/include
FORCE_INCLUDE += -include pch.hpp
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
ALL_LDFLAGS += $(LDFLAGS) -L/opt/homebrew/lib -arch arm64 -mmacosx-version-min=14.0
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = build/Bin/Debug
TARGET = $(TARGETDIR)/libDesert.a
OBJDIR = build/Intermediates/Debug/Debug/Desert
DEFINES += -DYAML_CPP_STATIC_DEFINE -DUSE_OPTICK=1 -DOPTICK_ENABLE_GPU=0 -DOPTICK_ENABLE_TRACING=0 -DDESERT_CONFIG_DEBUG -DDESERT_PLATFORM_MACOS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -arch arm64 -g -w -mmacosx-version-min=14.0
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -arch arm64 -g -w -std=c++20 -mmacosx-version-min=14.0
LIBS += build/Bin/Debug/libCommon.a build/Bin/Debug/libImGui.a build/Bin/Debug/libJolt.a build/Bin/Debug/libLua.a build/Bin/Debug/libOptick.a build/Bin/Debug/libMeshOptimizer.a build/Bin/Debug/libyaml-cpp.a build/Bin/Debug/libReflectCpp.a -lvulkan -lshaderc_combined -lspirv-cross-glsl -lspirv-cross-core
LDDEPS += build/Bin/Debug/libCommon.a build/Bin/Debug/libImGui.a build/Bin/Debug/libJolt.a build/Bin/Debug/libLua.a build/Bin/Debug/libOptick.a build/Bin/Debug/libMeshOptimizer.a build/Bin/Debug/libyaml-cpp.a build/Bin/Debug/libReflectCpp.a
define PREBUILDCMDS
	@echo Running prebuild commands
	"/Users/daniilsavcenko/Desktop/Programming/C++/DesertEngine/build/Bin/Debug/DesertHeaderTool" "/Users/daniilsavcenko/Desktop/Programming/C++/DesertEngine/Desert/Desert/Source" "/Users/daniilsavcenko/Desktop/Programming/C++/DesertEngine/Desert/Desert/Source/Engine/Generated/Reflection.gen.cpp" "Engine"
endef

else ifeq ($(config),release)
TARGETDIR = build/Bin/Release
TARGET = $(TARGETDIR)/libDesert.a
OBJDIR = build/Intermediates/Release/Release/Desert
DEFINES += -DNDEBUG -DYAML_CPP_STATIC_DEFINE -DUSE_OPTICK=1 -DOPTICK_ENABLE_GPU=0 -DOPTICK_ENABLE_TRACING=0 -DDESERT_CONFIG_RELEASE -DDESERT_PLATFORM_MACOS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -arch arm64 -O2 -w -mmacosx-version-min=14.0
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -arch arm64 -O2 -w -std=c++20 -mmacosx-version-min=14.0
LIBS += build/Bin/Release/libCommon.a build/Bin/Release/libImGui.a build/Bin/Release/libJolt.a build/Bin/Release/libLua.a build/Bin/Release/libOptick.a build/Bin/Release/libMeshOptimizer.a build/Bin/Release/libyaml-cpp.a build/Bin/Release/libReflectCpp.a -lvulkan -lshaderc_combined -lspirv-cross-glsl -lspirv-cross-core
LDDEPS += build/Bin/Release/libCommon.a build/Bin/Release/libImGui.a build/Bin/Release/libJolt.a build/Bin/Release/libLua.a build/Bin/Release/libOptick.a build/Bin/Release/libMeshOptimizer.a build/Bin/Release/libyaml-cpp.a build/Bin/Release/libReflectCpp.a
define PREBUILDCMDS
	@echo Running prebuild commands
	"/Users/daniilsavcenko/Desktop/Programming/C++/DesertEngine/build/Bin/Release/DesertHeaderTool" "/Users/daniilsavcenko/Desktop/Programming/C++/DesertEngine/Desert/Desert/Source" "/Users/daniilsavcenko/Desktop/Programming/C++/DesertEngine/Desert/Desert/Source/Engine/Generated/Reflection.gen.cpp" "Engine"
endef

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/AnimGraphEvaluator.o
GENERATED += $(OBJDIR)/AnimGraphSerialization.o
GENERATED += $(OBJDIR)/AnimatedImageService.o
GENERATED += $(OBJDIR)/AnimationAsset.o
GENERATED += $(OBJDIR)/AnimationClip.o
GENERATED += $(OBJDIR)/AnimationLibrary.o
GENERATED += $(OBJDIR)/Animator.o
GENERATED += $(OBJDIR)/Application.o
GENERATED += $(OBJDIR)/AssetHotReload.o
GENERATED += $(OBJDIR)/AssetPreloader.o
GENERATED += $(OBJDIR)/AudioBindings.o
GENERATED += $(OBJDIR)/AudioEngine.o
GENERATED += $(OBJDIR)/AutoExposureRenderer.o
GENERATED += $(OBJDIR)/AutoRig.o
GENERATED += $(OBJDIR)/BRDFLut.o
GENERATED += $(OBJDIR)/BloomRenderer.o
GENERATED += $(OBJDIR)/Camera.o
GENERATED += $(OBJDIR)/CharacterBindings.o
GENERATED += $(OBJDIR)/CommandBufferAllocator.o
GENERATED += $(OBJDIR)/ComponentRegistry.o
GENERATED += $(OBJDIR)/ComputeImages.o
GENERATED += $(OBJDIR)/DShaderParser.o
GENERATED += $(OBJDIR)/Device.o
GENERATED += $(OBJDIR)/DrawList2D.o
GENERATED += $(OBJDIR)/DynamicMesh.o
GENERATED += $(OBJDIR)/EngineContext.o
GENERATED += $(OBJDIR)/EngineStats.o
GENERATED += $(OBJDIR)/Entity.o
GENERATED += $(OBJDIR)/EntityCoreBindings.o
GENERATED += $(OBJDIR)/EntitySerializer.o
GENERATED += $(OBJDIR)/FXAARenderer.o
GENERATED += $(OBJDIR)/FallbackTextures.o
GENERATED += $(OBJDIR)/FontBaker.o
GENERATED += $(OBJDIR)/FontService.o
GENERATED += $(OBJDIR)/Framebuffer.o
GENERATED += $(OBJDIR)/Frustum.o
GENERATED += $(OBJDIR)/ImGuiBuild.o
GENERATED += $(OBJDIR)/ImGuiRenderer.o
GENERATED += $(OBJDIR)/Image.o
GENERATED += $(OBJDIR)/ImageReader.o
GENERATED += $(OBJDIR)/ImageService.o
GENERATED += $(OBJDIR)/IndexBuffer.o
GENERATED += $(OBJDIR)/Input.o
GENERATED += $(OBJDIR)/InputBindings.o
GENERATED += $(OBJDIR)/JumpFloodMaterials.o
GENERATED += $(OBJDIR)/JumpFloodOutlineRenderer.o
GENERATED += $(OBJDIR)/LVK.o
GENERATED += $(OBJDIR)/LogBindings.o
GENERATED += $(OBJDIR)/MacOSWindow.o
GENERATED += $(OBJDIR)/Material.o
GENERATED += $(OBJDIR)/MaterialBindings.o
GENERATED += $(OBJDIR)/MaterialExecutor.o
GENERATED += $(OBJDIR)/MaterialFXAA.o
GENERATED += $(OBJDIR)/MaterialFactory.o
GENERATED += $(OBJDIR)/MaterialInstance.o
GENERATED += $(OBJDIR)/MaterialJFAComposite.o
GENERATED += $(OBJDIR)/MaterialPBRBase.o
GENERATED += $(OBJDIR)/MaterialProperty.o
GENERATED += $(OBJDIR)/MaterialSMAA.o
GENERATED += $(OBJDIR)/MaterialService.o
GENERATED += $(OBJDIR)/MaterialShadow.o
GENERATED += $(OBJDIR)/MaterialSilhouette.o
GENERATED += $(OBJDIR)/MaterialSkybox.o
GENERATED += $(OBJDIR)/MaterialTonemap.o
GENERATED += $(OBJDIR)/MeshAsset.o
GENERATED += $(OBJDIR)/MeshLOD.o
GENERATED += $(OBJDIR)/MeshRenderer.o
GENERATED += $(OBJDIR)/MeshService.o
GENERATED += $(OBJDIR)/MeshSimplifier.o
GENERATED += $(OBJDIR)/MipMapGenerator.o
GENERATED += $(OBJDIR)/ParticleRenderer.o
GENERATED += $(OBJDIR)/PhysicsWorld.o
GENERATED += $(OBJDIR)/Pipeline.o
GENERATED += $(OBJDIR)/Pose.o
GENERATED += $(OBJDIR)/PrefabAsset.o
GENERATED += $(OBJDIR)/PrefabFactory.o
GENERATED += $(OBJDIR)/PrimitiveMeshFactory.o
GENERATED += $(OBJDIR)/ProceduralCharacterAnimations.o
GENERATED += $(OBJDIR)/ProceduralCharacterFactory.o
GENERATED += $(OBJDIR)/ProjectContext.o
GENERATED += $(OBJDIR)/Reflection.gen.o
GENERATED += $(OBJDIR)/ReflectionBindings.o
GENERATED += $(OBJDIR)/ReflectionRegistry.o
GENERATED += $(OBJDIR)/ReflectionSerializer.o
GENERATED += $(OBJDIR)/Render2D.o
GENERATED += $(OBJDIR)/RenderGraphBuilder.o
GENERATED += $(OBJDIR)/RenderPass.o
GENERATED += $(OBJDIR)/RenderPhaseRegistry.o
GENERATED += $(OBJDIR)/Renderer.o
GENERATED += $(OBJDIR)/RendererContext.o
GENERATED += $(OBJDIR)/ResourceRegistry.o
GENERATED += $(OBJDIR)/SMAARenderer.o
GENERATED += $(OBJDIR)/Scene.o
GENERATED += $(OBJDIR)/SceneEnvironment.o
GENERATED += $(OBJDIR)/SceneRenderer.o
GENERATED += $(OBJDIR)/SceneSerializer.o
GENERATED += $(OBJDIR)/ScriptEngine.o
GENERATED += $(OBJDIR)/Shader.o
GENERATED += $(OBJDIR)/ShaderAsset.o
GENERATED += $(OBJDIR)/ShaderCompiler.o
GENERATED += $(OBJDIR)/ShaderIncluder.o
GENERATED += $(OBJDIR)/ShaderPreprocessor.o
GENERATED += $(OBJDIR)/ShaderResourcesManager.o
GENERATED += $(OBJDIR)/ShaderService.o
GENERATED += $(OBJDIR)/Skeleton.o
GENERATED += $(OBJDIR)/SkeletonAsset.o
GENERATED += $(OBJDIR)/SkinnedMaterialPBR.o
GENERATED += $(OBJDIR)/SkinnedMesh.o
GENERATED += $(OBJDIR)/SkinnedMeshAsset.o
GENERATED += $(OBJDIR)/SkyboxAsset.o
GENERATED += $(OBJDIR)/SkyboxRenderer.o
GENERATED += $(OBJDIR)/SkyboxService.o
GENERATED += $(OBJDIR)/StaticMaterialPBR.o
GENERATED += $(OBJDIR)/StaticMesh.o
GENERATED += $(OBJDIR)/StaticMeshAsset.o
GENERATED += $(OBJDIR)/StorageBuffer.o
GENERATED += $(OBJDIR)/SurfaceMaterialAsset.o
GENERATED += $(OBJDIR)/SwapChain.o
GENERATED += $(OBJDIR)/TerrainRenderer.o
GENERATED += $(OBJDIR)/Texture.o
GENERATED += $(OBJDIR)/TextureAsset.o
GENERATED += $(OBJDIR)/TextureService.o
GENERATED += $(OBJDIR)/TimerBindings.o
GENERATED += $(OBJDIR)/TonemapRenderer.o
GENERATED += $(OBJDIR)/UICacheTexture.o
GENERATED += $(OBJDIR)/UICacheTextureImGui.o
GENERATED += $(OBJDIR)/UICanvasRenderer.o
GENERATED += $(OBJDIR)/UICanvasRenderer2D.o
GENERATED += $(OBJDIR)/UniformBuffer.o
GENERATED += $(OBJDIR)/UniformImage2D.o
GENERATED += $(OBJDIR)/UniformImageCube.o
GENERATED += $(OBJDIR)/VertexBuffer.o
GENERATED += $(OBJDIR)/VideoService.o
GENERATED += $(OBJDIR)/VulkanAllocator.o
GENERATED += $(OBJDIR)/VulkanClasses.o
GENERATED += $(OBJDIR)/VulkanContext.o
GENERATED += $(OBJDIR)/VulkanDevice.o
GENERATED += $(OBJDIR)/VulkanFallbackTextures.o
GENERATED += $(OBJDIR)/VulkanFramebuffer.o
GENERATED += $(OBJDIR)/VulkanHelper.o
GENERATED += $(OBJDIR)/VulkanImGuiLayer.o
GENERATED += $(OBJDIR)/VulkanImage.o
GENERATED += $(OBJDIR)/VulkanIndexBuffer.o
GENERATED += $(OBJDIR)/VulkanMaterialBackend.o
GENERATED += $(OBJDIR)/VulkanMipMapGenerator.o
GENERATED += $(OBJDIR)/VulkanPipeline.o
GENERATED += $(OBJDIR)/VulkanPipelineCompute.o
GENERATED += $(OBJDIR)/VulkanQueue.o
GENERATED += $(OBJDIR)/VulkanRenderCommandBuffer.o
GENERATED += $(OBJDIR)/VulkanRenderer.o
GENERATED += $(OBJDIR)/VulkanShader.o
GENERATED += $(OBJDIR)/VulkanStorageBuffer.o
GENERATED += $(OBJDIR)/VulkanSwapChain.o
GENERATED += $(OBJDIR)/VulkanUniformBuffer.o
GENERATED += $(OBJDIR)/VulkanUniformImage2D.o
GENERATED += $(OBJDIR)/VulkanUniformImageCube.o
GENERATED += $(OBJDIR)/VulkanUtils.o
GENERATED += $(OBJDIR)/VulkanVertexBuffer.o
GENERATED += $(OBJDIR)/Window.o
GENERATED += $(OBJDIR)/WorldBindings.o
GENERATED += $(OBJDIR)/WriteDescriptorSetBuilder.o
GENERATED += $(OBJDIR)/imGuiLayer.o
GENERATED += $(OBJDIR)/miniaudio.o
GENERATED += $(OBJDIR)/pch.o
GENERATED += $(OBJDIR)/pl_mpeg.o
GENERATED += $(OBJDIR)/stb_image.o
GENERATED += $(OBJDIR)/stb_truetype.o
GENERATED += $(OBJDIR)/vk_mem_alloc.o
OBJECTS += $(OBJDIR)/AnimGraphEvaluator.o
OBJECTS += $(OBJDIR)/AnimGraphSerialization.o
OBJECTS += $(OBJDIR)/AnimatedImageService.o
OBJECTS += $(OBJDIR)/AnimationAsset.o
OBJECTS += $(OBJDIR)/AnimationClip.o
OBJECTS += $(OBJDIR)/AnimationLibrary.o
OBJECTS += $(OBJDIR)/Animator.o
OBJECTS += $(OBJDIR)/Application.o
OBJECTS += $(OBJDIR)/AssetHotReload.o
OBJECTS += $(OBJDIR)/AssetPreloader.o
OBJECTS += $(OBJDIR)/AudioBindings.o
OBJECTS += $(OBJDIR)/AudioEngine.o
OBJECTS += $(OBJDIR)/AutoExposureRenderer.o
OBJECTS += $(OBJDIR)/AutoRig.o
OBJECTS += $(OBJDIR)/BRDFLut.o
OBJECTS += $(OBJDIR)/BloomRenderer.o
OBJECTS += $(OBJDIR)/Camera.o
OBJECTS += $(OBJDIR)/CharacterBindings.o
OBJECTS += $(OBJDIR)/CommandBufferAllocator.o
OBJECTS += $(OBJDIR)/ComponentRegistry.o
OBJECTS += $(OBJDIR)/ComputeImages.o
OBJECTS += $(OBJDIR)/DShaderParser.o
OBJECTS += $(OBJDIR)/Device.o
OBJECTS += $(OBJDIR)/DrawList2D.o
OBJECTS += $(OBJDIR)/DynamicMesh.o
OBJECTS += $(OBJDIR)/EngineContext.o
OBJECTS += $(OBJDIR)/EngineStats.o
OBJECTS += $(OBJDIR)/Entity.o
OBJECTS += $(OBJDIR)/EntityCoreBindings.o
OBJECTS += $(OBJDIR)/EntitySerializer.o
OBJECTS += $(OBJDIR)/FXAARenderer.o
OBJECTS += $(OBJDIR)/FallbackTextures.o
OBJECTS += $(OBJDIR)/FontBaker.o
OBJECTS += $(OBJDIR)/FontService.o
OBJECTS += $(OBJDIR)/Framebuffer.o
OBJECTS += $(OBJDIR)/Frustum.o
OBJECTS += $(OBJDIR)/ImGuiBuild.o
OBJECTS += $(OBJDIR)/ImGuiRenderer.o
OBJECTS += $(OBJDIR)/Image.o
OBJECTS += $(OBJDIR)/ImageReader.o
OBJECTS += $(OBJDIR)/ImageService.o
OBJECTS += $(OBJDIR)/IndexBuffer.o
OBJECTS += $(OBJDIR)/Input.o
OBJECTS += $(OBJDIR)/InputBindings.o
OBJECTS += $(OBJDIR)/JumpFloodMaterials.o
OBJECTS += $(OBJDIR)/JumpFloodOutlineRenderer.o
OBJECTS += $(OBJDIR)/LVK.o
OBJECTS += $(OBJDIR)/LogBindings.o
OBJECTS += $(OBJDIR)/MacOSWindow.o
OBJECTS += $(OBJDIR)/Material.o
OBJECTS += $(OBJDIR)/MaterialBindings.o
OBJECTS += $(OBJDIR)/MaterialExecutor.o
OBJECTS += $(OBJDIR)/MaterialFXAA.o
OBJECTS += $(OBJDIR)/MaterialFactory.o
OBJECTS += $(OBJDIR)/MaterialInstance.o
OBJECTS += $(OBJDIR)/MaterialJFAComposite.o
OBJECTS += $(OBJDIR)/MaterialPBRBase.o
OBJECTS += $(OBJDIR)/MaterialProperty.o
OBJECTS += $(OBJDIR)/MaterialSMAA.o
OBJECTS += $(OBJDIR)/MaterialService.o
OBJECTS += $(OBJDIR)/MaterialShadow.o
OBJECTS += $(OBJDIR)/MaterialSilhouette.o
OBJECTS += $(OBJDIR)/MaterialSkybox.o
OBJECTS += $(OBJDIR)/MaterialTonemap.o
OBJECTS += $(OBJDIR)/MeshAsset.o
OBJECTS += $(OBJDIR)/MeshLOD.o
OBJECTS += $(OBJDIR)/MeshRenderer.o
OBJECTS += $(OBJDIR)/MeshService.o
OBJECTS += $(OBJDIR)/MeshSimplifier.o
OBJECTS += $(OBJDIR)/MipMapGenerator.o
OBJECTS += $(OBJDIR)/ParticleRenderer.o
OBJECTS += $(OBJDIR)/PhysicsWorld.o
OBJECTS += $(OBJDIR)/Pipeline.o
OBJECTS += $(OBJDIR)/Pose.o
OBJECTS += $(OBJDIR)/PrefabAsset.o
OBJECTS += $(OBJDIR)/PrefabFactory.o
OBJECTS += $(OBJDIR)/PrimitiveMeshFactory.o
OBJECTS += $(OBJDIR)/ProceduralCharacterAnimations.o
OBJECTS += $(OBJDIR)/ProceduralCharacterFactory.o
OBJECTS += $(OBJDIR)/ProjectContext.o
OBJECTS += $(OBJDIR)/Reflection.gen.o
OBJECTS += $(OBJDIR)/ReflectionBindings.o
OBJECTS += $(OBJDIR)/ReflectionRegistry.o
OBJECTS += $(OBJDIR)/ReflectionSerializer.o
OBJECTS += $(OBJDIR)/Render2D.o
OBJECTS += $(OBJDIR)/RenderGraphBuilder.o
OBJECTS += $(OBJDIR)/RenderPass.o
OBJECTS += $(OBJDIR)/RenderPhaseRegistry.o
OBJECTS += $(OBJDIR)/Renderer.o
OBJECTS += $(OBJDIR)/RendererContext.o
OBJECTS += $(OBJDIR)/ResourceRegistry.o
OBJECTS += $(OBJDIR)/SMAARenderer.o
OBJECTS += $(OBJDIR)/Scene.o
OBJECTS += $(OBJDIR)/SceneEnvironment.o
OBJECTS += $(OBJDIR)/SceneRenderer.o
OBJECTS += $(OBJDIR)/SceneSerializer.o
OBJECTS += $(OBJDIR)/ScriptEngine.o
OBJECTS += $(OBJDIR)/Shader.o
OBJECTS += $(OBJDIR)/ShaderAsset.o
OBJECTS += $(OBJDIR)/ShaderCompiler.o
OBJECTS += $(OBJDIR)/ShaderIncluder.o
OBJECTS += $(OBJDIR)/ShaderPreprocessor.o
OBJECTS += $(OBJDIR)/ShaderResourcesManager.o
OBJECTS += $(OBJDIR)/ShaderService.o
OBJECTS += $(OBJDIR)/Skeleton.o
OBJECTS += $(OBJDIR)/SkeletonAsset.o
OBJECTS += $(OBJDIR)/SkinnedMaterialPBR.o
OBJECTS += $(OBJDIR)/SkinnedMesh.o
OBJECTS += $(OBJDIR)/SkinnedMeshAsset.o
OBJECTS += $(OBJDIR)/SkyboxAsset.o
OBJECTS += $(OBJDIR)/SkyboxRenderer.o
OBJECTS += $(OBJDIR)/SkyboxService.o
OBJECTS += $(OBJDIR)/StaticMaterialPBR.o
OBJECTS += $(OBJDIR)/StaticMesh.o
OBJECTS += $(OBJDIR)/StaticMeshAsset.o
OBJECTS += $(OBJDIR)/StorageBuffer.o
OBJECTS += $(OBJDIR)/SurfaceMaterialAsset.o
OBJECTS += $(OBJDIR)/SwapChain.o
OBJECTS += $(OBJDIR)/TerrainRenderer.o
OBJECTS += $(OBJDIR)/Texture.o
OBJECTS += $(OBJDIR)/TextureAsset.o
OBJECTS += $(OBJDIR)/TextureService.o
OBJECTS += $(OBJDIR)/TimerBindings.o
OBJECTS += $(OBJDIR)/TonemapRenderer.o
OBJECTS += $(OBJDIR)/UICacheTexture.o
OBJECTS += $(OBJDIR)/UICacheTextureImGui.o
OBJECTS += $(OBJDIR)/UICanvasRenderer.o
OBJECTS += $(OBJDIR)/UICanvasRenderer2D.o
OBJECTS += $(OBJDIR)/UniformBuffer.o
OBJECTS += $(OBJDIR)/UniformImage2D.o
OBJECTS += $(OBJDIR)/UniformImageCube.o
OBJECTS += $(OBJDIR)/VertexBuffer.o
OBJECTS += $(OBJDIR)/VideoService.o
OBJECTS += $(OBJDIR)/VulkanAllocator.o
OBJECTS += $(OBJDIR)/VulkanClasses.o
OBJECTS += $(OBJDIR)/VulkanContext.o
OBJECTS += $(OBJDIR)/VulkanDevice.o
OBJECTS += $(OBJDIR)/VulkanFallbackTextures.o
OBJECTS += $(OBJDIR)/VulkanFramebuffer.o
OBJECTS += $(OBJDIR)/VulkanHelper.o
OBJECTS += $(OBJDIR)/VulkanImGuiLayer.o
OBJECTS += $(OBJDIR)/VulkanImage.o
OBJECTS += $(OBJDIR)/VulkanIndexBuffer.o
OBJECTS += $(OBJDIR)/VulkanMaterialBackend.o
OBJECTS += $(OBJDIR)/VulkanMipMapGenerator.o
OBJECTS += $(OBJDIR)/VulkanPipeline.o
OBJECTS += $(OBJDIR)/VulkanPipelineCompute.o
OBJECTS += $(OBJDIR)/VulkanQueue.o
OBJECTS += $(OBJDIR)/VulkanRenderCommandBuffer.o
OBJECTS += $(OBJDIR)/VulkanRenderer.o
OBJECTS += $(OBJDIR)/VulkanShader.o
OBJECTS += $(OBJDIR)/VulkanStorageBuffer.o
OBJECTS += $(OBJDIR)/VulkanSwapChain.o
OBJECTS += $(OBJDIR)/VulkanUniformBuffer.o
OBJECTS += $(OBJDIR)/VulkanUniformImage2D.o
OBJECTS += $(OBJDIR)/VulkanUniformImageCube.o
OBJECTS += $(OBJDIR)/VulkanUtils.o
OBJECTS += $(OBJDIR)/VulkanVertexBuffer.o
OBJECTS += $(OBJDIR)/Window.o
OBJECTS += $(OBJDIR)/WorldBindings.o
OBJECTS += $(OBJDIR)/WriteDescriptorSetBuilder.o
OBJECTS += $(OBJDIR)/imGuiLayer.o
OBJECTS += $(OBJDIR)/miniaudio.o
OBJECTS += $(OBJDIR)/pch.o
OBJECTS += $(OBJDIR)/pl_mpeg.o
OBJECTS += $(OBJDIR)/stb_image.o
OBJECTS += $(OBJDIR)/stb_truetype.o
OBJECTS += $(OBJDIR)/vk_mem_alloc.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking Desert
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning Desert
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/AnimationClip.o: Desert/Desert/Source/Engine/Animation/AnimationClip.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AnimationLibrary.o: Desert/Desert/Source/Engine/Animation/AnimationLibrary.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Animator.o: Desert/Desert/Source/Engine/Animation/Animator.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AnimGraphEvaluator.o: Desert/Desert/Source/Engine/Animation/Graph/AnimGraphEvaluator.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AnimGraphSerialization.o: Desert/Desert/Source/Engine/Animation/Graph/AnimGraphSerialization.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Pose.o: Desert/Desert/Source/Engine/Animation/Pose.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ProceduralCharacterAnimations.o: Desert/Desert/Source/Engine/Animation/ProceduralCharacterAnimations.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Skeleton.o: Desert/Desert/Source/Engine/Animation/Skeleton.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AssetPreloader.o: Desert/Desert/Source/Engine/Assets/AssetPreloader.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AnimationAsset.o: Desert/Desert/Source/Engine/Assets/Mesh/AnimationAsset.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MeshAsset.o: Desert/Desert/Source/Engine/Assets/Mesh/MeshAsset.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SkeletonAsset.o: Desert/Desert/Source/Engine/Assets/Mesh/SkeletonAsset.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SkinnedMeshAsset.o: Desert/Desert/Source/Engine/Assets/Mesh/SkinnedMeshAsset.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/StaticMeshAsset.o: Desert/Desert/Source/Engine/Assets/Mesh/StaticMeshAsset.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SurfaceMaterialAsset.o: Desert/Desert/Source/Engine/Assets/Mesh/SurfaceMaterialAsset.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PrefabAsset.o: Desert/Desert/Source/Engine/Assets/Prefab/PrefabAsset.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ShaderAsset.o: Desert/Desert/Source/Engine/Assets/Shader/ShaderAsset.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SkyboxAsset.o: Desert/Desert/Source/Engine/Assets/Skybox/SkyboxAsset.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TextureAsset.o: Desert/Desert/Source/Engine/Assets/TextureAsset.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AudioEngine.o: Desert/Desert/Source/Engine/Audio/AudioEngine.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Application.o: Desert/Desert/Source/Engine/Core/Application.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Camera.o: Desert/Desert/Source/Engine/Core/Camera.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Device.o: Desert/Desert/Source/Engine/Core/Device.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EngineContext.o: Desert/Desert/Source/Engine/Core/EngineContext.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EngineStats.o: Desert/Desert/Source/Engine/Core/EngineStats.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Frustum.o: Desert/Desert/Source/Engine/Core/Frustum.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImageReader.o: Desert/Desert/Source/Engine/Core/IO/ImageReader.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Input.o: Desert/Desert/Source/Engine/Core/Input.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Scene.o: Desert/Desert/Source/Engine/Core/Scene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ComponentRegistry.o: Desert/Desert/Source/Engine/Core/Serialize/ComponentRegistry.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EntitySerializer.o: Desert/Desert/Source/Engine/Core/Serialize/EntitySerializer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SceneSerializer.o: Desert/Desert/Source/Engine/Core/Serialize/SceneSerializer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DShaderParser.o: Desert/Desert/Source/Engine/Core/ShaderCompiler/DShader/DShaderParser.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ShaderIncluder.o: Desert/Desert/Source/Engine/Core/ShaderCompiler/Includer/ShaderIncluder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ShaderCompiler.o: Desert/Desert/Source/Engine/Core/ShaderCompiler/ShaderCompiler.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ShaderPreprocessor.o: Desert/Desert/Source/Engine/Core/ShaderCompiler/ShaderPreprocess/ShaderPreprocessor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Window.o: Desert/Desert/Source/Engine/Core/Window.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Entity.o: Desert/Desert/Source/Engine/ECS/Entity.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Reflection.gen.o: Desert/Desert/Source/Engine/Generated/Reflection.gen.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AutoRig.o: Desert/Desert/Source/Engine/Geometry/AutoRig.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DynamicMesh.o: Desert/Desert/Source/Engine/Geometry/DynamicMesh.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MeshLOD.o: Desert/Desert/Source/Engine/Geometry/MeshLOD.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MeshSimplifier.o: Desert/Desert/Source/Engine/Geometry/MeshSimplifier.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PrimitiveMeshFactory.o: Desert/Desert/Source/Engine/Geometry/PrimitiveMeshFactory.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ProceduralCharacterFactory.o: Desert/Desert/Source/Engine/Geometry/ProceduralCharacterFactory.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SkinnedMesh.o: Desert/Desert/Source/Engine/Geometry/SkinnedMesh.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/StaticMesh.o: Desert/Desert/Source/Engine/Geometry/StaticMesh.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CommandBufferAllocator.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/CommandBufferAllocator.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanAllocator.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanAllocator.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanContext.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanContext.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanDevice.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanDevice.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanFallbackTextures.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanFallbackTextures.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanFramebuffer.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanFramebuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanImage.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanImage.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanIndexBuffer.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanIndexBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanMaterialBackend.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanMaterialBackend.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanMipMapGenerator.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanMipMapGenerator.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanPipeline.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanPipeline.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanPipelineCompute.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanPipelineCompute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanQueue.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanQueue.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanRenderCommandBuffer.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanRenderCommandBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanRenderer.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanShader.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanShader.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanSwapChain.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanSwapChain.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanHelper.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanUtils/VulkanHelper.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WriteDescriptorSetBuilder.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanUtils/WriteDescriptorSetBuilder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LVK.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanUtils/lightweightvk/LVK.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanClasses.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanUtils/lightweightvk/VulkanClasses.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanUtils.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanUtils/lightweightvk/VulkanUtils.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanVertexBuffer.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/VulkanVertexBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImGuiRenderer.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/imgui/ImGuiRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanImGuiLayer.o: Desert/Desert/Source/Engine/Graphic/API/Vulkan/imgui/VulkanImGuiLayer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BRDFLut.o: Desert/Desert/Source/Engine/Graphic/BRDFLut.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ComputeImages.o: Desert/Desert/Source/Engine/Graphic/ComputeImages.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SceneEnvironment.o: Desert/Desert/Source/Engine/Graphic/Environment/SceneEnvironment.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FallbackTextures.o: Desert/Desert/Source/Engine/Graphic/FallbackTextures.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Framebuffer.o: Desert/Desert/Source/Engine/Graphic/Framebuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Image.o: Desert/Desert/Source/Engine/Graphic/Image.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IndexBuffer.o: Desert/Desert/Source/Engine/Graphic/IndexBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Material.o: Desert/Desert/Source/Engine/Graphic/Materials/Material.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialExecutor.o: Desert/Desert/Source/Engine/Graphic/Materials/MaterialExecutor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialFactory.o: Desert/Desert/Source/Engine/Graphic/Materials/MaterialFactory.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialInstance.o: Desert/Desert/Source/Engine/Graphic/Materials/MaterialInstance.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialProperty.o: Desert/Desert/Source/Engine/Graphic/Materials/MaterialProperty.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialShadow.o: Desert/Desert/Source/Engine/Graphic/Materials/Mesh/MaterialShadow.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialSilhouette.o: Desert/Desert/Source/Engine/Graphic/Materials/Mesh/MaterialSilhouette.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialPBRBase.o: Desert/Desert/Source/Engine/Graphic/Materials/Mesh/PBR/MaterialPBRBase.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SkinnedMaterialPBR.o: Desert/Desert/Source/Engine/Graphic/Materials/Mesh/PBR/SkinnedMaterialPBR.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/StaticMaterialPBR.o: Desert/Desert/Source/Engine/Graphic/Materials/Mesh/PBR/StaticMaterialPBR.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/JumpFloodMaterials.o: Desert/Desert/Source/Engine/Graphic/Materials/PostProcessing/JumpFloodMaterials.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialFXAA.o: Desert/Desert/Source/Engine/Graphic/Materials/PostProcessing/MaterialFXAA.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialJFAComposite.o: Desert/Desert/Source/Engine/Graphic/Materials/PostProcessing/MaterialJFAComposite.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialSMAA.o: Desert/Desert/Source/Engine/Graphic/Materials/PostProcessing/MaterialSMAA.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialTonemap.o: Desert/Desert/Source/Engine/Graphic/Materials/PostProcessing/MaterialTonemap.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialSkybox.o: Desert/Desert/Source/Engine/Graphic/Materials/Skybox/MaterialSkybox.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MipMapGenerator.o: Desert/Desert/Source/Engine/Graphic/MipMapGenerator.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Pipeline.o: Desert/Desert/Source/Engine/Graphic/Pipeline.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DrawList2D.o: Desert/Desert/Source/Engine/Graphic/Render2D/DrawList2D.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Render2D.o: Desert/Desert/Source/Engine/Graphic/Render2D/Render2D.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RenderGraphBuilder.o: Desert/Desert/Source/Engine/Graphic/RenderGraphBuilder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RenderPass.o: Desert/Desert/Source/Engine/Graphic/RenderPass.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RenderPhaseRegistry.o: Desert/Desert/Source/Engine/Graphic/RenderPhaseRegistry.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Renderer.o: Desert/Desert/Source/Engine/Graphic/Renderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RendererContext.o: Desert/Desert/Source/Engine/Graphic/RendererContext.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SceneRenderer.o: Desert/Desert/Source/Engine/Graphic/SceneRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Shader.o: Desert/Desert/Source/Engine/Graphic/Shader.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SwapChain.o: Desert/Desert/Source/Engine/Graphic/SwapChain.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MeshRenderer.o: Desert/Desert/Source/Engine/Graphic/Systems/Scene/Mesh/MeshRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParticleRenderer.o: Desert/Desert/Source/Engine/Graphic/Systems/Scene/Particles/ParticleRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AutoExposureRenderer.o: Desert/Desert/Source/Engine/Graphic/Systems/Scene/PostProcessing/AutoExposureRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BloomRenderer.o: Desert/Desert/Source/Engine/Graphic/Systems/Scene/PostProcessing/BloomRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FXAARenderer.o: Desert/Desert/Source/Engine/Graphic/Systems/Scene/PostProcessing/FXAARenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/JumpFloodOutlineRenderer.o: Desert/Desert/Source/Engine/Graphic/Systems/Scene/PostProcessing/JumpFloodOutlineRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SMAARenderer.o: Desert/Desert/Source/Engine/Graphic/Systems/Scene/PostProcessing/SMAARenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TonemapRenderer.o: Desert/Desert/Source/Engine/Graphic/Systems/Scene/PostProcessing/TonemapRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SkyboxRenderer.o: Desert/Desert/Source/Engine/Graphic/Systems/Scene/Skybox/SkyboxRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TerrainRenderer.o: Desert/Desert/Source/Engine/Graphic/Systems/Scene/Terrain/TerrainRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Texture.o: Desert/Desert/Source/Engine/Graphic/Texture.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UICacheTexture.o: Desert/Desert/Source/Engine/Graphic/UICacheTexture.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VertexBuffer.o: Desert/Desert/Source/Engine/Graphic/VertexBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PhysicsWorld.o: Desert/Desert/Source/Engine/Physics/PhysicsWorld.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ProjectContext.o: Desert/Desert/Source/Engine/Project/ProjectContext.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ReflectionRegistry.o: Desert/Desert/Source/Engine/Reflection/ReflectionRegistry.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ReflectionSerializer.o: Desert/Desert/Source/Engine/Reflection/ReflectionSerializer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AssetHotReload.o: Desert/Desert/Source/Engine/Runtime/AssetHotReload.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PrefabFactory.o: Desert/Desert/Source/Engine/Runtime/Factory/PrefabFactory.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ResourceRegistry.o: Desert/Desert/Source/Engine/Runtime/ResourceRegistry.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AnimatedImageService.o: Desert/Desert/Source/Engine/Runtime/Services/AnimatedImage/AnimatedImageService.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FontService.o: Desert/Desert/Source/Engine/Runtime/Services/Font/FontService.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImageService.o: Desert/Desert/Source/Engine/Runtime/Services/Image/ImageService.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialService.o: Desert/Desert/Source/Engine/Runtime/Services/Material/MaterialService.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MeshService.o: Desert/Desert/Source/Engine/Runtime/Services/Mesh/MeshService.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ShaderService.o: Desert/Desert/Source/Engine/Runtime/Services/Shader/ShaderService.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SkyboxService.o: Desert/Desert/Source/Engine/Runtime/Services/Skybox/SkyboxService.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TextureService.o: Desert/Desert/Source/Engine/Runtime/Services/Texture/TextureService.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VideoService.o: Desert/Desert/Source/Engine/Runtime/Services/Video/VideoService.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AudioBindings.o: Desert/Desert/Source/Engine/Scripting/AudioBindings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CharacterBindings.o: Desert/Desert/Source/Engine/Scripting/CharacterBindings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EntityCoreBindings.o: Desert/Desert/Source/Engine/Scripting/EntityCoreBindings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/InputBindings.o: Desert/Desert/Source/Engine/Scripting/InputBindings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LogBindings.o: Desert/Desert/Source/Engine/Scripting/LogBindings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialBindings.o: Desert/Desert/Source/Engine/Scripting/MaterialBindings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ReflectionBindings.o: Desert/Desert/Source/Engine/Scripting/ReflectionBindings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ScriptEngine.o: Desert/Desert/Source/Engine/Scripting/ScriptEngine.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TimerBindings.o: Desert/Desert/Source/Engine/Scripting/TimerBindings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WorldBindings.o: Desert/Desert/Source/Engine/Scripting/WorldBindings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanStorageBuffer.o: Desert/Desert/Source/Engine/ShaderResources/API/Vulkan/VulkanStorageBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanUniformBuffer.o: Desert/Desert/Source/Engine/ShaderResources/API/Vulkan/VulkanUniformBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanUniformImage2D.o: Desert/Desert/Source/Engine/ShaderResources/API/Vulkan/VulkanUniformImage2D.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VulkanUniformImageCube.o: Desert/Desert/Source/Engine/ShaderResources/API/Vulkan/VulkanUniformImageCube.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ShaderResourcesManager.o: Desert/Desert/Source/Engine/ShaderResources/ShaderResourcesManager.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/StorageBuffer.o: Desert/Desert/Source/Engine/ShaderResources/StorageBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UniformBuffer.o: Desert/Desert/Source/Engine/ShaderResources/UniformBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UniformImage2D.o: Desert/Desert/Source/Engine/ShaderResources/UniformImage2D.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UniformImageCube.o: Desert/Desert/Source/Engine/ShaderResources/UniformImageCube.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FontBaker.o: Desert/Desert/Source/Engine/Text/FontBaker.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UICanvasRenderer.o: Desert/Desert/Source/Engine/UI/UICanvasRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UICanvasRenderer2D.o: Desert/Desert/Source/Engine/UI/UICanvasRenderer2D.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImGuiBuild.o: Desert/Desert/Source/Engine/imgui/ImGuiBuild.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UICacheTextureImGui.o: Desert/Desert/Source/Engine/imgui/UICacheTextureImGui.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imGuiLayer.o: Desert/Desert/Source/Engine/imgui/imGuiLayer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MacOSWindow.o: Desert/Desert/Source/Platform/MacOS/MacOSWindow.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pch.o: Desert/Desert/Source/pch.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vk_mem_alloc.o: ThirdParty/VulkanAllocator/vk_mem_alloc.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/miniaudio.o: ThirdParty/miniaudio/miniaudio.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pl_mpeg.o: ThirdParty/pl_mpeg/pl_mpeg.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stb_image.o: ThirdParty/stb/stb_image.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stb_truetype.o: ThirdParty/stb/stb_truetype.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif