# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -IDesert/Desert/Source -IEditor/Source -IDesert/Common/Source -IThirdParty/spdlog/include -IThirdParty/GLFW/include -IThirdParty/Glad/include -IThirdParty/entt/include -IThirdParty/ImGui -IThirdParty/glm -IThirdParty/optick/src -IThirdParty -IEditor/ThirdParty/ImGuizmo -IThirdParty/reflect-cpp/include -IThirdParty/stb/include -I/opt/homebrew/include -IThirdParty/dlib
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
ALL_LDFLAGS += $(LDFLAGS) -L/opt/homebrew/lib -arch arm64 -mmacosx-version-min=14.0
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = build/Bin/Debug
TARGET = $(TARGETDIR)/Editor
OBJDIR = build/Intermediates/Debug/Debug/Editor
DEFINES += -DYAML_CPP_STATIC_DEFINE -DUSE_OPTICK=1 -DOPTICK_ENABLE_GPU=0 -DOPTICK_ENABLE_TRACING=0 -DDESERT_WITH_DLIB -DDESERT_CONFIG_DEBUG -DDESERT_PLATFORM_MACOS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -arch arm64 -g -w -mmacosx-version-min=14.0
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -arch arm64 -g -w -std=c++20 -mmacosx-version-min=14.0
LIBS += build/Bin/Debug/libDesert.a build/Bin/Debug/libyaml-cpp.a build/Bin/Debug/libGLFW.a build/Bin/Debug/libOptick.a build/Bin/Debug/libMeshOptimizer.a build/Bin/Debug/libImGuiNodeEditor.a build/Bin/Debug/libDlib.a build/Bin/Debug/libCommon.a build/Bin/Debug/libImGui.a build/Bin/Debug/libJolt.a build/Bin/Debug/libLua.a build/Bin/Debug/libReflectCpp.a -framework Cocoa -framework IOKit -framework CoreFoundation -framework CoreVideo -framework CoreMedia -framework AVFoundation -framework QuartzCore -lassimp -lvulkan -lshaderc_combined -lspirv-cross-glsl -lspirv-cross-core
LDDEPS += build/Bin/Debug/libDesert.a build/Bin/Debug/libyaml-cpp.a build/Bin/Debug/libGLFW.a build/Bin/Debug/libOptick.a build/Bin/Debug/libMeshOptimizer.a build/Bin/Debug/libImGuiNodeEditor.a build/Bin/Debug/libDlib.a build/Bin/Debug/libCommon.a build/Bin/Debug/libImGui.a build/Bin/Debug/libJolt.a build/Bin/Debug/libLua.a build/Bin/Debug/libReflectCpp.a

else ifeq ($(config),release)
TARGETDIR = build/Bin/Release
TARGET = $(TARGETDIR)/Editor
OBJDIR = build/Intermediates/Release/Release/Editor
DEFINES += -DNDEBUG -DYAML_CPP_STATIC_DEFINE -DUSE_OPTICK=1 -DOPTICK_ENABLE_GPU=0 -DOPTICK_ENABLE_TRACING=0 -DDESERT_WITH_DLIB -DDESERT_CONFIG_RELEASE -DDESERT_PLATFORM_MACOS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -arch arm64 -O2 -w -mmacosx-version-min=14.0
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -arch arm64 -O2 -w -std=c++20 -mmacosx-version-min=14.0
LIBS += build/Bin/Release/libDesert.a build/Bin/Release/libyaml-cpp.a build/Bin/Release/libGLFW.a build/Bin/Release/libOptick.a build/Bin/Release/libMeshOptimizer.a build/Bin/Release/libImGuiNodeEditor.a build/Bin/Release/libDlib.a build/Bin/Release/libCommon.a build/Bin/Release/libImGui.a build/Bin/Release/libJolt.a build/Bin/Release/libLua.a build/Bin/Release/libReflectCpp.a -framework Cocoa -framework IOKit -framework CoreFoundation -framework CoreVideo -framework CoreMedia -framework AVFoundation -framework QuartzCore -lassimp -lvulkan -lshaderc_combined -lspirv-cross-glsl -lspirv-cross-core
LDDEPS += build/Bin/Release/libDesert.a build/Bin/Release/libyaml-cpp.a build/Bin/Release/libGLFW.a build/Bin/Release/libOptick.a build/Bin/Release/libMeshOptimizer.a build/Bin/Release/libImGuiNodeEditor.a build/Bin/Release/libDlib.a build/Bin/Release/libCommon.a build/Bin/Release/libImGui.a build/Bin/Release/libJolt.a build/Bin/Release/libLua.a build/Bin/Release/libReflectCpp.a

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/AnimGraphPanel.o
GENERATED += $(OBJDIR)/AnimLayersPanel.o
GENERATED += $(OBJDIR)/AnimationComponentWidget.o
GENERATED += $(OBJDIR)/AssetFileOps.o
GENERATED += $(OBJDIR)/AssetReferences.o
GENERATED += $(OBJDIR)/AssetReferencesPanel.o
GENERATED += $(OBJDIR)/AssetReferencesScan.o
GENERATED += $(OBJDIR)/AssetThumbnailRenderer.o
GENERATED += $(OBJDIR)/AssimpImporter.o
GENERATED += $(OBJDIR)/BuildSettingsPanel.o
GENERATED += $(OBJDIR)/BuiltinMeshRegistry.o
GENERATED += $(OBJDIR)/CollectionsPanel.o
GENERATED += $(OBJDIR)/CommandPalette.o
GENERATED += $(OBJDIR)/ComponentEditor.o
GENERATED += $(OBJDIR)/ComponentEditorRegistrations.o
GENERATED += $(OBJDIR)/ComponentMultiEdit.o
GENERATED += $(OBJDIR)/ComponentWidgetRegistry.o
GENERATED += $(OBJDIR)/Controls.o
GENERATED += $(OBJDIR)/CrashRecovery.o
GENERATED += $(OBJDIR)/CubeGridTool.o
GENERATED += $(OBJDIR)/EditorColliderPass.o
GENERATED += $(OBJDIR)/EditorGridPass.o
GENERATED += $(OBJDIR)/EditorLayer.o
GENERATED += $(OBJDIR)/EditorPreferences.o
GENERATED += $(OBJDIR)/EditorResources.o
GENERATED += $(OBJDIR)/EditorUIPass.o
GENERATED += $(OBJDIR)/FaceTracker.o
GENERATED += $(OBJDIR)/FileExplorerPanel.o
GENERATED += $(OBJDIR)/FoliagePaintTool.o
GENERATED += $(OBJDIR)/FuzzyMatch.o
GENERATED += $(OBJDIR)/GamePackager.o
GENERATED += $(OBJDIR)/GizmoController.o
GENERATED += $(OBJDIR)/HistoryPanel.o
GENERATED += $(OBJDIR)/ImGuiUI.o
GENERATED += $(OBJDIR)/ImGuiUtilities.o
GENERATED += $(OBJDIR)/ImGuizmo.o
GENERATED += $(OBJDIR)/ImportManager.o
GENERATED += $(OBJDIR)/LODFold.o
GENERATED += $(OBJDIR)/LayoutManager.o
GENERATED += $(OBJDIR)/LightGizmoRenderer.o
GENERATED += $(OBJDIR)/LogView.o
GENERATED += $(OBJDIR)/LogsPanel.o
GENERATED += $(OBJDIR)/LuaConsolePanel.o
GENERATED += $(OBJDIR)/MaterialsPanelComponent.o
GENERATED += $(OBJDIR)/MeshDetailsWidget.o
GENERATED += $(OBJDIR)/MeshDnD.o
GENERATED += $(OBJDIR)/MeshEditorPanel.o
GENERATED += $(OBJDIR)/MeshMaterial.o
GENERATED += $(OBJDIR)/ModelingPanel.o
GENERATED += $(OBJDIR)/MultiEdit.o
GENERATED += $(OBJDIR)/NodeGraphPanel.o
GENERATED += $(OBJDIR)/ParticleEditorPanel.o
GENERATED += $(OBJDIR)/PerfHudOverlay.o
GENERATED += $(OBJDIR)/PhotogrammetryPanel.o
GENERATED += $(OBJDIR)/PickingController.o
GENERATED += $(OBJDIR)/PolyEditTool.o
GENERATED += $(OBJDIR)/PrefabComponentWidget.o
GENERATED += $(OBJDIR)/PropertyEditorBuilder.o
GENERATED += $(OBJDIR)/RenderRigistry.o
GENERATED += $(OBJDIR)/RigBuilder.o
GENERATED += $(OBJDIR)/Sandbox.o
GENERATED += $(OBJDIR)/SceneCommands.o
GENERATED += $(OBJDIR)/SceneHierarchyPanel.o
GENERATED += $(OBJDIR)/ScenePropertiesPanel.o
GENERATED += $(OBJDIR)/SceneSettingsPanel.o
GENERATED += $(OBJDIR)/SceneValidationPanel.o
GENERATED += $(OBJDIR)/SelectionManager.o
GENERATED += $(OBJDIR)/SequencerPanel.o
GENERATED += $(OBJDIR)/ShaderGraph.o
GENERATED += $(OBJDIR)/ShaderLibraryPanel.o
GENERATED += $(OBJDIR)/SkinnedMeshComponentWidget.o
GENERATED += $(OBJDIR)/SkyboxComponent.o
GENERATED += $(OBJDIR)/StaticMeshComponent.o
GENERATED += $(OBJDIR)/TerrainPaintTool.o
GENERATED += $(OBJDIR)/TextureDnD.o
GENERATED += $(OBJDIR)/TextureImporter.o
GENERATED += $(OBJDIR)/ThemeManager.o
GENERATED += $(OBJDIR)/ThumbnailCache.o
GENERATED += $(OBJDIR)/TransformComponentWidget.o
GENERATED += $(OBJDIR)/UIEditorPanel.o
GENERATED += $(OBJDIR)/ViewportPanel.o
OBJECTS += $(OBJDIR)/AnimGraphPanel.o
OBJECTS += $(OBJDIR)/AnimLayersPanel.o
OBJECTS += $(OBJDIR)/AnimationComponentWidget.o
OBJECTS += $(OBJDIR)/AssetFileOps.o
OBJECTS += $(OBJDIR)/AssetReferences.o
OBJECTS += $(OBJDIR)/AssetReferencesPanel.o
OBJECTS += $(OBJDIR)/AssetReferencesScan.o
OBJECTS += $(OBJDIR)/AssetThumbnailRenderer.o
OBJECTS += $(OBJDIR)/AssimpImporter.o
OBJECTS += $(OBJDIR)/BuildSettingsPanel.o
OBJECTS += $(OBJDIR)/BuiltinMeshRegistry.o
OBJECTS += $(OBJDIR)/CollectionsPanel.o
OBJECTS += $(OBJDIR)/CommandPalette.o
OBJECTS += $(OBJDIR)/ComponentEditor.o
OBJECTS += $(OBJDIR)/ComponentEditorRegistrations.o
OBJECTS += $(OBJDIR)/ComponentMultiEdit.o
OBJECTS += $(OBJDIR)/ComponentWidgetRegistry.o
OBJECTS += $(OBJDIR)/Controls.o
OBJECTS += $(OBJDIR)/CrashRecovery.o
OBJECTS += $(OBJDIR)/CubeGridTool.o
OBJECTS += $(OBJDIR)/EditorColliderPass.o
OBJECTS += $(OBJDIR)/EditorGridPass.o
OBJECTS += $(OBJDIR)/EditorLayer.o
OBJECTS += $(OBJDIR)/EditorPreferences.o
OBJECTS += $(OBJDIR)/EditorResources.o
OBJECTS += $(OBJDIR)/EditorUIPass.o
OBJECTS += $(OBJDIR)/FaceTracker.o
OBJECTS += $(OBJDIR)/FileExplorerPanel.o
OBJECTS += $(OBJDIR)/FoliagePaintTool.o
OBJECTS += $(OBJDIR)/FuzzyMatch.o
OBJECTS += $(OBJDIR)/GamePackager.o
OBJECTS += $(OBJDIR)/GizmoController.o
OBJECTS += $(OBJDIR)/HistoryPanel.o
OBJECTS += $(OBJDIR)/ImGuiUI.o
OBJECTS += $(OBJDIR)/ImGuiUtilities.o
OBJECTS += $(OBJDIR)/ImGuizmo.o
OBJECTS += $(OBJDIR)/ImportManager.o
OBJECTS += $(OBJDIR)/LODFold.o
OBJECTS += $(OBJDIR)/LayoutManager.o
OBJECTS += $(OBJDIR)/LightGizmoRenderer.o
OBJECTS += $(OBJDIR)/LogView.o
OBJECTS += $(OBJDIR)/LogsPanel.o
OBJECTS += $(OBJDIR)/LuaConsolePanel.o
OBJECTS += $(OBJDIR)/MaterialsPanelComponent.o
OBJECTS += $(OBJDIR)/MeshDetailsWidget.o
OBJECTS += $(OBJDIR)/MeshDnD.o
OBJECTS += $(OBJDIR)/MeshEditorPanel.o
OBJECTS += $(OBJDIR)/MeshMaterial.o
OBJECTS += $(OBJDIR)/ModelingPanel.o
OBJECTS += $(OBJDIR)/MultiEdit.o
OBJECTS += $(OBJDIR)/NodeGraphPanel.o
OBJECTS += $(OBJDIR)/ParticleEditorPanel.o
OBJECTS += $(OBJDIR)/PerfHudOverlay.o
OBJECTS += $(OBJDIR)/PhotogrammetryPanel.o
OBJECTS += $(OBJDIR)/PickingController.o
OBJECTS += $(OBJDIR)/PolyEditTool.o
OBJECTS += $(OBJDIR)/PrefabComponentWidget.o
OBJECTS += $(OBJDIR)/PropertyEditorBuilder.o
OBJECTS += $(OBJDIR)/RenderRigistry.o
OBJECTS += $(OBJDIR)/RigBuilder.o
OBJECTS += $(OBJDIR)/Sandbox.o
OBJECTS += $(OBJDIR)/SceneCommands.o
OBJECTS += $(OBJDIR)/SceneHierarchyPanel.o
OBJECTS += $(OBJDIR)/ScenePropertiesPanel.o
OBJECTS += $(OBJDIR)/SceneSettingsPanel.o
OBJECTS += $(OBJDIR)/SceneValidationPanel.o
OBJECTS += $(OBJDIR)/SelectionManager.o
OBJECTS += $(OBJDIR)/SequencerPanel.o
OBJECTS += $(OBJDIR)/ShaderGraph.o
OBJECTS += $(OBJDIR)/ShaderLibraryPanel.o
OBJECTS += $(OBJDIR)/SkinnedMeshComponentWidget.o
OBJECTS += $(OBJDIR)/SkyboxComponent.o
OBJECTS += $(OBJDIR)/StaticMeshComponent.o
OBJECTS += $(OBJDIR)/TerrainPaintTool.o
OBJECTS += $(OBJDIR)/TextureDnD.o
OBJECTS += $(OBJDIR)/TextureImporter.o
OBJECTS += $(OBJDIR)/ThemeManager.o
OBJECTS += $(OBJDIR)/ThumbnailCache.o
OBJECTS += $(OBJDIR)/TransformComponentWidget.o
OBJECTS += $(OBJDIR)/UIEditorPanel.o
OBJECTS += $(OBJDIR)/ViewportPanel.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking Editor
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning Editor
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/BuiltinMeshRegistry.o: Editor/Source/Editor/Builtin/BuiltinMeshRegistry.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AssetFileOps.o: Editor/Source/Editor/Core/AssetFileOps.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AssetReferences.o: Editor/Source/Editor/Core/AssetReferences.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AssetReferencesScan.o: Editor/Source/Editor/Core/AssetReferencesScan.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CommandPalette.o: Editor/Source/Editor/Core/CommandPalette.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SceneCommands.o: Editor/Source/Editor/Core/Commands/SceneCommands.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CrashRecovery.o: Editor/Source/Editor/Core/CrashRecovery.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EditorPreferences.o: Editor/Source/Editor/Core/EditorPreferences.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EditorResources.o: Editor/Source/Editor/Core/EditorResources.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FuzzyMatch.o: Editor/Source/Editor/Core/FuzzyMatch.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImGuiUtilities.o: Editor/Source/Editor/Core/ImGuiUtilities.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LayoutManager.o: Editor/Source/Editor/Core/LayoutManager.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LogView.o: Editor/Source/Editor/Core/LogView.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MultiEdit.o: Editor/Source/Editor/Core/MultiEdit.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RigBuilder.o: Editor/Source/Editor/Core/Rigging/RigBuilder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SelectionManager.o: Editor/Source/Editor/Core/Selection/SelectionManager.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ThemeManager.o: Editor/Source/Editor/Core/ThemeManager.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AssimpImporter.o: Editor/Source/Editor/Import/Assimp/AssimpImporter.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImportManager.o: Editor/Source/Editor/Import/ImportManager.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LODFold.o: Editor/Source/Editor/Import/LODFold.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MeshDnD.o: Editor/Source/Editor/Import/MeshDnD.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MeshMaterial.o: Editor/Source/Editor/Import/MeshMaterial.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TextureDnD.o: Editor/Source/Editor/Import/TextureDnD.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TextureImporter.o: Editor/Source/Editor/Import/TextureImporter.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GamePackager.o: Editor/Source/Editor/Packaging/GamePackager.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AnimGraphPanel.o: Editor/Source/Editor/Panels/Animation/AnimGraphPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AnimLayersPanel.o: Editor/Source/Editor/Panels/Animation/AnimLayersPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AssetReferencesPanel.o: Editor/Source/Editor/Panels/AssetReferences/AssetReferencesPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CollectionsPanel.o: Editor/Source/Editor/Panels/Collections/CollectionsPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ShaderLibraryPanel.o: Editor/Source/Editor/Panels/Debug/ShaderLibraryPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FileExplorerPanel.o: Editor/Source/Editor/Panels/FileExplorer/FileExplorerPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/HistoryPanel.o: Editor/Source/Editor/Panels/History/HistoryPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LogsPanel.o: Editor/Source/Editor/Panels/Logs/LogsPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LuaConsolePanel.o: Editor/Source/Editor/Panels/LuaConsole/LuaConsolePanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MeshEditorPanel.o: Editor/Source/Editor/Panels/MeshEditor/MeshEditorPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ModelingPanel.o: Editor/Source/Editor/Panels/Modeling/ModelingPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/NodeGraphPanel.o: Editor/Source/Editor/Panels/NodeGraph/NodeGraphPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ShaderGraph.o: Editor/Source/Editor/Panels/NodeGraph/ShaderGraph.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParticleEditorPanel.o: Editor/Source/Editor/Panels/Particles/ParticleEditorPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PhotogrammetryPanel.o: Editor/Source/Editor/Panels/Photogrammetry/PhotogrammetryPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ComponentMultiEdit.o: Editor/Source/Editor/Panels/PropertyEditor/ComponentMultiEdit.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ComponentWidgetRegistry.o: Editor/Source/Editor/Panels/PropertyEditor/ComponentWidgetRegistry.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PropertyEditorBuilder.o: Editor/Source/Editor/Panels/PropertyEditor/PropertyEditorBuilder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SceneHierarchyPanel.o: Editor/Source/Editor/Panels/SceneHierarchy/SceneHierarchyPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ComponentEditor.o: Editor/Source/Editor/Panels/SceneProperties/ComponentEditor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ComponentEditorRegistrations.o: Editor/Source/Editor/Panels/SceneProperties/ComponentEditorRegistrations.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AnimationComponentWidget.o: Editor/Source/Editor/Panels/SceneProperties/ComponentWidgets/AnimationComponentWidget.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MeshDetailsWidget.o: Editor/Source/Editor/Panels/SceneProperties/ComponentWidgets/Helper/MeshDetailsWidget.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MaterialsPanelComponent.o: Editor/Source/Editor/Panels/SceneProperties/ComponentWidgets/MaterialsPanelComponent.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PrefabComponentWidget.o: Editor/Source/Editor/Panels/SceneProperties/ComponentWidgets/PrefabComponentWidget.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SkinnedMeshComponentWidget.o: Editor/Source/Editor/Panels/SceneProperties/ComponentWidgets/SkinnedMeshComponentWidget.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SkyboxComponent.o: Editor/Source/Editor/Panels/SceneProperties/ComponentWidgets/SkyboxComponent.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/StaticMeshComponent.o: Editor/Source/Editor/Panels/SceneProperties/ComponentWidgets/StaticMeshComponent.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TransformComponentWidget.o: Editor/Source/Editor/Panels/SceneProperties/ComponentWidgets/TransformComponentWidget.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ScenePropertiesPanel.o: Editor/Source/Editor/Panels/SceneProperties/ScenePropertiesPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SceneSettingsPanel.o: Editor/Source/Editor/Panels/SceneSettings/SceneSettingsPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BuildSettingsPanel.o: Editor/Source/Editor/Panels/Stubs/BuildSettingsPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SequencerPanel.o: Editor/Source/Editor/Panels/Stubs/SequencerPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UIEditorPanel.o: Editor/Source/Editor/Panels/UI/UIEditorPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SceneValidationPanel.o: Editor/Source/Editor/Panels/Validation/SceneValidationPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LightGizmoRenderer.o: Editor/Source/Editor/Panels/ViewportPanel/LightGizmoRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PerfHudOverlay.o: Editor/Source/Editor/Panels/ViewportPanel/PerfHudOverlay.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CubeGridTool.o: Editor/Source/Editor/Panels/ViewportPanel/Tools/CubeGridTool.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FoliagePaintTool.o: Editor/Source/Editor/Panels/ViewportPanel/Tools/FoliagePaintTool.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GizmoController.o: Editor/Source/Editor/Panels/ViewportPanel/Tools/GizmoController.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PickingController.o: Editor/Source/Editor/Panels/ViewportPanel/Tools/PickingController.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PolyEditTool.o: Editor/Source/Editor/Panels/ViewportPanel/Tools/PolyEditTool.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TerrainPaintTool.o: Editor/Source/Editor/Panels/ViewportPanel/Tools/TerrainPaintTool.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ViewportPanel.o: Editor/Source/Editor/Panels/ViewportPanel/ViewportPanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EditorColliderPass.o: Editor/Source/Editor/RenderSystems/Passes/EditorColliderPass.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EditorGridPass.o: Editor/Source/Editor/RenderSystems/Passes/EditorGridPass.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EditorUIPass.o: Editor/Source/Editor/RenderSystems/Passes/EditorUIPass.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RenderRigistry.o: Editor/Source/Editor/RenderSystems/RenderRigistry.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AssetThumbnailRenderer.o: Editor/Source/Editor/Widgets/AssetThumbnailRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Controls.o: Editor/Source/Editor/Widgets/Controls/Controls.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FaceTracker.o: Editor/Source/Editor/Widgets/FaceTracker.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ThumbnailCache.o: Editor/Source/Editor/Widgets/ThumbnailCache.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImGuiUI.o: Editor/Source/Editor/Widgets/UIHelper/ImGuiUI.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EditorLayer.o: Editor/Source/EditorLayer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Sandbox.o: Editor/Source/Sandbox.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImGuizmo.o: Editor/ThirdParty/ImGuizmo/ImGuizmo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif