# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  ImGui_config = debug
  ImGuiNodeEditor_config = debug
  yaml_cpp_config = debug
  Jolt_config = debug
  Lua_config = debug
  Optick_config = debug
  MeshOptimizer_config = debug
  Dlib_config = debug
  ReflectCpp_config = debug
  DesertHeaderTool_config = debug
  FbxMeshSplitter_config = debug
  ProjectHub_config = debug
  DShaderTool_config = debug
  PakTool_config = debug
  Desert_config = debug
  Common_config = debug
  Editor_config = debug
  Runtime_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  ImGui_config = release
  ImGuiNodeEditor_config = release
  yaml_cpp_config = release
  Jolt_config = release
  Lua_config = release
  Optick_config = release
  MeshOptimizer_config = release
  Dlib_config = release
  ReflectCpp_config = release
  DesertHeaderTool_config = release
  FbxMeshSplitter_config = release
  ProjectHub_config = release
  DShaderTool_config = release
  PakTool_config = release
  Desert_config = release
  Common_config = release
  Editor_config = release
  Runtime_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW ImGui ImGuiNodeEditor yaml-cpp Jolt Lua Optick MeshOptimizer Dlib ReflectCpp DesertHeaderTool FbxMeshSplitter ProjectHub DShaderTool PakTool Desert Common Editor Runtime

.PHONY: all clean help $(PROJECTS) ThirdParty Tools

all: $(PROJECTS)

ThirdParty: Dlib GLFW ImGui ImGuiNodeEditor Jolt Lua MeshOptimizer Optick ReflectCpp yaml-cpp

Tools: DShaderTool DesertHeaderTool FbxMeshSplitter PakTool ProjectHub

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C ThirdParty/GLFW -f Makefile config=$(GLFW_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C ThirdParty/ImGui -f Makefile config=$(ImGui_config)
endif

ImGuiNodeEditor: ImGui
ifneq (,$(ImGuiNodeEditor_config))
	@echo "==== Building ImGuiNodeEditor ($(ImGuiNodeEditor_config)) ===="
	@${MAKE} --no-print-directory -C ThirdParty/imgui-node-editor -f Makefile config=$(ImGuiNodeEditor_config)
endif

yaml-cpp:
ifneq (,$(yaml_cpp_config))
	@echo "==== Building yaml-cpp ($(yaml_cpp_config)) ===="
	@${MAKE} --no-print-directory -C build/Projects/YamlCpp -f Makefile config=$(yaml_cpp_config)
endif

Jolt:
ifneq (,$(Jolt_config))
	@echo "==== Building Jolt ($(Jolt_config)) ===="
	@${MAKE} --no-print-directory -C build/Projects/Jolt -f Makefile config=$(Jolt_config)
endif

Lua:
ifneq (,$(Lua_config))
	@echo "==== Building Lua ($(Lua_config)) ===="
	@${MAKE} --no-print-directory -C build/Projects/Lua -f Makefile config=$(Lua_config)
endif

Optick:
ifneq (,$(Optick_config))
	@echo "==== Building Optick ($(Optick_config)) ===="
	@${MAKE} --no-print-directory -C build/Projects/Optick -f Makefile config=$(Optick_config)
endif

MeshOptimizer:
ifneq (,$(MeshOptimizer_config))
	@echo "==== Building MeshOptimizer ($(MeshOptimizer_config)) ===="
	@${MAKE} --no-print-directory -C build/Projects/MeshOptimizer -f Makefile config=$(MeshOptimizer_config)
endif

Dlib:
ifneq (,$(Dlib_config))
	@echo "==== Building Dlib ($(Dlib_config)) ===="
	@${MAKE} --no-print-directory -C build/Projects/Dlib -f Makefile config=$(Dlib_config)
endif

ReflectCpp:
ifneq (,$(ReflectCpp_config))
	@echo "==== Building ReflectCpp ($(ReflectCpp_config)) ===="
	@${MAKE} --no-print-directory -C build/Projects/ReflectCpp -f Makefile config=$(ReflectCpp_config)
endif

DesertHeaderTool:
ifneq (,$(DesertHeaderTool_config))
	@echo "==== Building DesertHeaderTool ($(DesertHeaderTool_config)) ===="
	@${MAKE} --no-print-directory -C . -f DesertHeaderTool.make config=$(DesertHeaderTool_config)
endif

FbxMeshSplitter:
ifneq (,$(FbxMeshSplitter_config))
	@echo "==== Building FbxMeshSplitter ($(FbxMeshSplitter_config)) ===="
	@${MAKE} --no-print-directory -C . -f FbxMeshSplitter.make config=$(FbxMeshSplitter_config)
endif

ProjectHub: ImGui GLFW Common
ifneq (,$(ProjectHub_config))
	@echo "==== Building ProjectHub ($(ProjectHub_config)) ===="
	@${MAKE} --no-print-directory -C . -f ProjectHub.make config=$(ProjectHub_config)
endif

DShaderTool: Common
ifneq (,$(DShaderTool_config))
	@echo "==== Building DShaderTool ($(DShaderTool_config)) ===="
	@${MAKE} --no-print-directory -C . -f DShaderTool.make config=$(DShaderTool_config)
endif

PakTool: Common
ifneq (,$(PakTool_config))
	@echo "==== Building PakTool ($(PakTool_config)) ===="
	@${MAKE} --no-print-directory -C . -f PakTool.make config=$(PakTool_config)
endif

Desert: Common ImGui Jolt Lua Optick MeshOptimizer yaml-cpp ReflectCpp DesertHeaderTool
ifneq (,$(Desert_config))
	@echo "==== Building Desert ($(Desert_config)) ===="
	@${MAKE} --no-print-directory -C . -f Desert.make config=$(Desert_config)
endif

Common: yaml-cpp Optick
ifneq (,$(Common_config))
	@echo "==== Building Common ($(Common_config)) ===="
	@${MAKE} --no-print-directory -C . -f Common.make config=$(Common_config)
endif

Editor: Desert yaml-cpp GLFW Optick MeshOptimizer ImGuiNodeEditor Dlib Common ImGui Jolt Lua ReflectCpp
ifneq (,$(Editor_config))
	@echo "==== Building Editor ($(Editor_config)) ===="
	@${MAKE} --no-print-directory -C . -f Editor.make config=$(Editor_config)
endif

Runtime: Desert yaml-cpp GLFW Optick MeshOptimizer Common Jolt Lua ReflectCpp
ifneq (,$(Runtime_config))
	@echo "==== Building Runtime ($(Runtime_config)) ===="
	@${MAKE} --no-print-directory -C . -f Runtime.make config=$(Runtime_config)
endif

clean:
	@${MAKE} --no-print-directory -C ThirdParty/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C ThirdParty/ImGui -f Makefile clean
	@${MAKE} --no-print-directory -C ThirdParty/imgui-node-editor -f Makefile clean
	@${MAKE} --no-print-directory -C build/Projects/YamlCpp -f Makefile clean
	@${MAKE} --no-print-directory -C build/Projects/Jolt -f Makefile clean
	@${MAKE} --no-print-directory -C build/Projects/Lua -f Makefile clean
	@${MAKE} --no-print-directory -C build/Projects/Optick -f Makefile clean
	@${MAKE} --no-print-directory -C build/Projects/MeshOptimizer -f Makefile clean
	@${MAKE} --no-print-directory -C build/Projects/Dlib -f Makefile clean
	@${MAKE} --no-print-directory -C build/Projects/ReflectCpp -f Makefile clean
	@${MAKE} --no-print-directory -C . -f DesertHeaderTool.make clean
	@${MAKE} --no-print-directory -C . -f FbxMeshSplitter.make clean
	@${MAKE} --no-print-directory -C . -f ProjectHub.make clean
	@${MAKE} --no-print-directory -C . -f DShaderTool.make clean
	@${MAKE} --no-print-directory -C . -f PakTool.make clean
	@${MAKE} --no-print-directory -C . -f Desert.make clean
	@${MAKE} --no-print-directory -C . -f Common.make clean
	@${MAKE} --no-print-directory -C . -f Editor.make clean
	@${MAKE} --no-print-directory -C . -f Runtime.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   ImGui"
	@echo "   ImGuiNodeEditor"
	@echo "   yaml-cpp"
	@echo "   Jolt"
	@echo "   Lua"
	@echo "   Optick"
	@echo "   MeshOptimizer"
	@echo "   Dlib"
	@echo "   ReflectCpp"
	@echo "   DesertHeaderTool"
	@echo "   FbxMeshSplitter"
	@echo "   ProjectHub"
	@echo "   DShaderTool"
	@echo "   PakTool"
	@echo "   Desert"
	@echo "   Common"
	@echo "   Editor"
	@echo "   Runtime"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"