# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -IDesert/Desert/Source -IRuntime/Source -IDesert/Common/Source -IThirdParty/spdlog/include -IThirdParty/GLFW/include -IThirdParty/Glad/include -IThirdParty/entt/include -IThirdParty/glm -IThirdParty/optick/src -IThirdParty -IRuntime/ThirdParty/ImGuizmo -IThirdParty/reflect-cpp/include -IThirdParty/stb/include -I/opt/homebrew/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
ALL_LDFLAGS += $(LDFLAGS) -L/opt/homebrew/lib -arch arm64 -mmacosx-version-min=14.0
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = build/Bin/Debug
TARGET = $(TARGETDIR)/Runtime
OBJDIR = build/Intermediates/Debug/Debug/Runtime
DEFINES += -DYAML_CPP_STATIC_DEFINE -DUSE_OPTICK=1 -DOPTICK_ENABLE_GPU=0 -DOPTICK_ENABLE_TRACING=0 -DDESERT_CONFIG_DEBUG -DDESERT_PLATFORM_MACOS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -arch arm64 -g -w -mmacosx-version-min=14.0
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -arch arm64 -g -w -std=c++20 -mmacosx-version-min=14.0
LIBS += build/Bin/Debug/libDesert.a build/Bin/Debug/libyaml-cpp.a build/Bin/Debug/libGLFW.a build/Bin/Debug/libOptick.a build/Bin/Debug/libMeshOptimizer.a build/Bin/Debug/libCommon.a build/Bin/Debug/libJolt.a build/Bin/Debug/libLua.a build/Bin/Debug/libReflectCpp.a -framework Cocoa -framework IOKit -framework CoreFoundation -framework CoreVideo -framework QuartzCore -lassimp -lvulkan -lshaderc_combined -lspirv-cross-glsl -lspirv-cross-core
LDDEPS += build/Bin/Debug/libDesert.a build/Bin/Debug/libyaml-cpp.a build/Bin/Debug/libGLFW.a build/Bin/Debug/libOptick.a build/Bin/Debug/libMeshOptimizer.a build/Bin/Debug/libCommon.a build/Bin/Debug/libJolt.a build/Bin/Debug/libLua.a build/Bin/Debug/libReflectCpp.a

else ifeq ($(config),release)
TARGETDIR = build/Bin/Release
TARGET = $(TARGETDIR)/Runtime
OBJDIR = build/Intermediates/Release/Release/Runtime
DEFINES += -DNDEBUG -DYAML_CPP_STATIC_DEFINE -DUSE_OPTICK=1 -DOPTICK_ENABLE_GPU=0 -DOPTICK_ENABLE_TRACING=0 -DDESERT_CONFIG_RELEASE -DDESERT_PLATFORM_MACOS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -arch arm64 -O2 -w -mmacosx-version-min=14.0
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -arch arm64 -O2 -w -std=c++20 -mmacosx-version-min=14.0
LIBS += build/Bin/Release/libDesert.a build/Bin/Release/libyaml-cpp.a build/Bin/Release/libGLFW.a build/Bin/Release/libOptick.a build/Bin/Release/libMeshOptimizer.a build/Bin/Release/libCommon.a build/Bin/Release/libJolt.a build/Bin/Release/libLua.a build/Bin/Release/libReflectCpp.a -framework Cocoa -framework IOKit -framework CoreFoundation -framework CoreVideo -framework QuartzCore -lassimp -lvulkan -lshaderc_combined -lspirv-cross-glsl -lspirv-cross-core
LDDEPS += build/Bin/Release/libDesert.a build/Bin/Release/libyaml-cpp.a build/Bin/Release/libGLFW.a build/Bin/Release/libOptick.a build/Bin/Release/libMeshOptimizer.a build/Bin/Release/libCommon.a build/Bin/Release/libJolt.a build/Bin/Release/libLua.a build/Bin/Release/libReflectCpp.a

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/Main.o
GENERATED += $(OBJDIR)/RuntimeLayer.o
OBJECTS += $(OBJDIR)/Main.o
OBJECTS += $(OBJDIR)/RuntimeLayer.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking Runtime
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning Runtime
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/Main.o: Runtime/Source/Main.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RuntimeLayer.o: Runtime/Source/RuntimeLayer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif