// GENERATED by the Desert Shader Graph editor — edit the .dgraph, not this file.
Shader "MatLitConst"
{
    Domain Surface

    State
    {
        Cull Back
        ZTest LEqual
        ZWrite On
    }

    Vertex
    {
        #define GRAPH_LIT 1
        #include <Common/GraphVertex.glslh>
    }

    Fragment
    {
        layout( location = 0 ) in vec2 v_UV;
        layout( location = 1 ) in vec3 v_Normal;
        layout( location = 0 ) out vec4 o_Color;

        #include <Common/DirectionLightsUB.glslh>

        void main()
        {
            vec4 n0 = vec4( 0.95, 0.55, 0.1, 1.0 );
            vec4 albedo = n0;
            vec3 N = normalize( v_Normal );
            vec3 L = normalize( -directionLights.directionLights.Direction.xyz );
            vec3 lightCol = directionLights.directionLights.ColorIntensity.rgb *
                            directionLights.directionLights.ColorIntensity.a;
            vec3 shaded = albedo.rgb * ( vec3( 0.12 ) + max( dot( N, L ), 0.0 ) * lightCol );
            o_Color = vec4( shaded + ( vec4( 0.0 ) ).rgb, albedo.a * ( 1.0 ) );
        }
    }
}
