@echo off
setlocal EnableDelayedExpansion
REM Generates Desert/Common/Source/Common/Core/Version.gen.hpp from git state:
REM   full version = <VERSION file>.<commit count>+<short hash>[.dirty]   e.g. 0.1.316+db43fdb
REM Windows counterpart of scripts/GenVersion.sh. Version.cpp includes the header behind
REM __has_include, so a build without this simply reports the fallback version.
REM
REM The file is rewritten ONLY when its content actually changes — an unchanged version must not
REM touch the timestamp, or every build would recompile Version.cpp and relink everything.

cd /d "%~dp0..\.."

set "BASE=0.0"
if exist VERSION (
    for /f "usebackq delims= " %%v in ("VERSION") do (
        set "BASE=%%v"
        goto :gotbase
    )
)
:gotbase

set "HASH=unknown"
set "BRANCH=unknown"
set "COUNT=0"
set "DIRTY=0"

where git >NUL 2>&1
if not errorlevel 1 (
    for /f "usebackq delims=" %%h in (`git rev-parse --short HEAD 2^>NUL`) do set "HASH=%%h"
    for /f "usebackq delims=" %%b in (`git rev-parse --abbrev-ref HEAD 2^>NUL`) do set "BRANCH=%%b"
    for /f "usebackq delims=" %%c in (`git rev-list --count HEAD 2^>NUL`) do set "COUNT=%%c"
    git diff-index --quiet HEAD -- 2>NUL
    if errorlevel 1 set "DIRTY=1"
)

set "OUT=Desert\Common\Source\Common\Core\Version.gen.hpp"
set "TMP=%TEMP%\Version.gen.hpp.%RANDOM%"

> "%TMP%" (
    echo // AUTO-GENERATED by scripts/Windows/GenVersion.bat — do not edit, do not commit.
    echo #pragma once
    echo #define DESERT_VERSION_BASE   "!BASE!"
    echo #define DESERT_VERSION_COMMITS !COUNT!u
    echo #define DESERT_VERSION_HASH   "!HASH!"
    echo #define DESERT_VERSION_BRANCH "!BRANCH!"
    echo #define DESERT_VERSION_DIRTY  !DIRTY!
)

if not exist "%OUT%" (
    move /Y "%TMP%" "%OUT%" >NUL
    echo --- Version: !BASE!.!COUNT!+!HASH! ^(branch !BRANCH!, dirty=!DIRTY!^)
) else (
    fc /B "%TMP%" "%OUT%" >NUL 2>&1
    if errorlevel 1 (
        move /Y "%TMP%" "%OUT%" >NUL
        echo --- Version: !BASE!.!COUNT!+!HASH! ^(branch !BRANCH!, dirty=!DIRTY!^)
    ) else (
        del /Q "%TMP%" >NUL 2>&1
    )
)
endlocal
