@echo off
setlocal EnableDelayedExpansion
REM Generates Desert\Common\Source\Common\Core\Version.gen.hpp from git state:
REM   full version = <VERSION file>.<commit count>+<short hash>[.dirty]   e.g. 0.1.1236+09e6d3b8
REM Windows counterpart of scripts/GenVersion.sh, and it must stay its exact mirror: the two write the
REM same macros and make the same decision about when a build number may be written at all.
REM
REM THE BUILD CALLS THIS. Until 2026-09-07 the only caller was scripts\Windows\Setup.bat, which runs
REM ONCE when a machine is prepared — so every msbuild after it, including every CI build, compiled a
REM header frozen at setup time. The caller is now Common.vcxproj's PreBuildEvent, declared in
REM Desert/Common/premake5.lua, which MSBuild runs on every build of every target that links Common.
REM
REM The file is rewritten ONLY when its content actually changes — an unchanged version must not
REM touch the timestamp, or every build would recompile Version.cpp and relink everything.

cd /d "%~dp0..\.."

set "BASE=0.0"
if exist VERSION (
    for /f "usebackq delims= " %%v in ("VERSION") do (
        set "BASE=%%v"
        goto :gotbase
    )
)
:gotbase

set "HASH=unknown"
set "BRANCH=unknown"
set "COUNT="
set "DIRTY=0"
REM THE BUILD NUMBER IS EITHER REAL OR ABSENT - there is no zero. `git rev-list --count HEAD` fails
REM without git and returns 1 on a SHALLOW clone, and either value written into the header is
REM indistinguishable from a genuinely young repository. The number is compared against a collection's
REM `EngineMinCommit` by the launcher, where "unknown" read as 0 blocks every download, so the macro is
REM emitted only when the count can be trusted and its absence is what Version.cpp reports.
set "COMMITS_LINE=// no build number: git could not supply a trustworthy one - see the build-time warning"

where git >NUL 2>&1
if errorlevel 1 goto :nogit

git rev-parse --verify HEAD >NUL 2>&1
if errorlevel 1 goto :nogit

for /f "usebackq delims=" %%h in (`git rev-parse --short HEAD 2^>NUL`) do set "HASH=%%h"
for /f "usebackq delims=" %%b in (`git rev-parse --abbrev-ref HEAD 2^>NUL`) do set "BRANCH=%%b"
REM `--refresh` first: on a cold index - a fresh clone, a CI runner - diff-index compares stat data it
REM has never validated and calls byte-identical files modified. Without it every CI artifact would be
REM stamped ".dirty", which is the same class of lie as a stale build number.
git update-index -q --refresh >NUL 2>&1
git diff-index --quiet HEAD -- 2>NUL
if errorlevel 1 set "DIRTY=1"

set "SHALLOW=true"
for /f "usebackq delims=" %%s in (`git rev-parse --is-shallow-repository 2^>NUL`) do set "SHALLOW=%%s"
if /i "!SHALLOW!"=="true" goto :shallow

for /f "usebackq delims=" %%c in (`git rev-list --count HEAD 2^>NUL`) do set "COUNT=%%c"
if defined COUNT set "COMMITS_LINE=#define DESERT_VERSION_COMMITS !COUNT!u"
goto :emit

:shallow
REM Redirection FIRST on every one of these: `echo text>&2` lets cmd swallow the character in front of
REM the `>` as a stream number, which is how the Windows test runner was blind for months.
>&2 echo [GenVersion] WARNING: shallow clone - this build gets NO build number.
>&2 echo [GenVersion]   'git rev-list --count HEAD' counts 1 here, which is a lie and not a number.
>&2 echo [GenVersion]   Fetch the full history - actions/checkout 'fetch-depth: 0' - to get one.
goto :emit

:nogit
>&2 echo [GenVersion] WARNING: no git HEAD under %CD% - this build gets NO build number and
>&2 echo [GenVersion]   reports its identity as '%BASE%+unknown'. Expected for a source archive;
>&2 echo [GenVersion]   inside a checkout it means git is missing or HEAD is unborn.

:emit
set "OUT=Desert\Common\Source\Common\Core\Version.gen.hpp"
set "TMP=%TEMP%\Version.gen.hpp.%RANDOM%"

> "%TMP%" (
    echo // AUTO-GENERATED by scripts/Windows/GenVersion.bat — do not edit, do not commit.
    echo #pragma once
    echo #define DESERT_VERSION_BASE   "!BASE!"
    echo !COMMITS_LINE!
    echo #define DESERT_VERSION_HASH   "!HASH!"
    echo #define DESERT_VERSION_BRANCH "!BRANCH!"
    echo #define DESERT_VERSION_DIRTY  !DIRTY!
)

if not exist "%OUT%" (
    move /Y "%TMP%" "%OUT%" >NUL
    echo --- Version: !BASE!.!COUNT!+!HASH! ^(branch !BRANCH!, dirty=!DIRTY!^)
) else (
    fc /B "%TMP%" "%OUT%" >NUL 2>&1
    if errorlevel 1 (
        move /Y "%TMP%" "%OUT%" >NUL
        echo --- Version: !BASE!.!COUNT!+!HASH! ^(branch !BRANCH!, dirty=!DIRTY!^)
    ) else (
        del /Q "%TMP%" >NUL 2>&1
    )
)
endlocal
