#!/usr/bin/env bash
# Generates Desert/Common/Source/Common/Core/Version.gen.hpp from git state:
#   full version = <VERSION file>.<commit count>+<short hash>[.dirty]   e.g. 0.1.1236+09e6d3b8
#
# THE BUILD CALLS THIS, AND NOTHING ELSE DOES. Until 2026-09-07 the only caller was
# scripts/MacOS/BuildMacOS.sh, so every `make` run by hand, by an agent or by the BuildSlot queue
# compiled whatever header happened to be lying on disk: this tree carried commit 492 while the
# repository was at 1233, a month stale. The caller is now the `Common` project itself
# (Desert/Common/premake5.lua), which every target that shows a version reaches through its link to
# Common — including Windows, where BuildMacOS.sh was never in the picture at all.
#
# The file is rewritten ONLY when its content actually changes, so an unchanged version never
# triggers rebuilds. That frugality is what made the staleness invisible for a month, and it is still
# the right behaviour now that the generator actually runs on every build.
set -euo pipefail
cd "$(dirname "$0")/.."

BASE="$(tr -d '[:space:]' < VERSION 2>/dev/null || echo 0.0)"

HASH="unknown"
BRANCH="unknown"
COUNT=""
DIRTY=0

# THE BUILD NUMBER IS EITHER REAL OR ABSENT — there is no zero, and that is the point of this block.
# `git rev-list --count HEAD` fails without git and returns **1** on a shallow clone (what
# actions/checkout hands us unless fetch-depth is 0). Both of those written into the header are
# indistinguishable from a genuinely young repository, and the number is not decoration: §4.4 of the
# launcher design compares it against a collection's `EngineMinCommit`, where "unknown" read as 0
# blocks every download. So DESERT_VERSION_COMMITS is emitted only when the count can be trusted, its
# absence is what Version.cpp reports as "no build number", and every untrusted case is LOUD here.
if git rev-parse --verify HEAD >/dev/null 2>&1; then
    HASH="$(git rev-parse --short HEAD)"
    BRANCH="$(git rev-parse --abbrev-ref HEAD)"
    # `--refresh` first: on a cold index (a fresh clone, a CI runner) diff-index compares stat data it
    # has never validated and reports files as modified that are byte-identical. Without this every CI
    # artifact would be stamped ".dirty", which is the same class of lie as a stale build number.
    git update-index -q --refresh || true
    git diff-index --quiet HEAD -- || DIRTY=1

    if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
        echo "[GenVersion] WARNING: shallow clone — this build gets NO build number." >&2
        echo "[GenVersion]   'git rev-list --count HEAD' counts 1 here, which is a lie and not a number." >&2
        echo "[GenVersion]   Fetch the full history (actions/checkout: 'fetch-depth: 0') to get one." >&2
    else
        COUNT="$(git rev-list --count HEAD)"
    fi
else
    echo "[GenVersion] WARNING: no git HEAD under $PWD — this build gets NO build number and" >&2
    echo "[GenVersion]   reports its identity as '${BASE}+unknown'. Expected for a source archive;" >&2
    echo "[GenVersion]   inside a checkout it means git is missing or HEAD is unborn." >&2
fi

COMMITS_LINE="// no build number: git could not supply a trustworthy one - see the build-time warning"
if [ -n "$COUNT" ]; then
    COMMITS_LINE="#define DESERT_VERSION_COMMITS ${COUNT}u"
fi

OUT="Desert/Common/Source/Common/Core/Version.gen.hpp"
NEW="// AUTO-GENERATED by scripts/GenVersion.sh — do not edit, do not commit.
#pragma once
#define DESERT_VERSION_BASE   \"${BASE}\"
${COMMITS_LINE}
#define DESERT_VERSION_HASH   \"${HASH}\"
#define DESERT_VERSION_BRANCH \"${BRANCH}\"
#define DESERT_VERSION_DIRTY  ${DIRTY}"

if [ ! -f "$OUT" ] || [ "$(cat "$OUT")" != "$NEW" ]; then
    printf '%s\n' "$NEW" > "$OUT"
    # Printed exactly as Common::Version::Full() will render it, so the build log and the status bar
    # cannot disagree about what this build is called.
    echo "--- Version: ${BASE}${COUNT:+.${COUNT}}+${HASH}$( [ "$DIRTY" = 1 ] && echo .dirty ) (branch ${BRANCH})"
fi
