#!/usr/bin/env bash
# Generates Desert/Common/Source/Common/Core/Version.gen.hpp from git state:
#   full version = <VERSION file>.<commit count>+<short hash>[.dirty]   e.g. 0.1.316+db43fdb
# The file is rewritten ONLY when its content actually changes, so an unchanged version never
# triggers rebuilds. Called by BuildMacOS.sh before premake; safe without git (falls back to 0).
set -euo pipefail
cd "$(dirname "$0")/.."

BASE="$(tr -d '[:space:]' < VERSION 2>/dev/null || echo 0.0)"
HASH="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
COUNT="$(git rev-list --count HEAD 2>/dev/null || echo 0)"
DIRTY=0
git diff-index --quiet HEAD -- 2>/dev/null || DIRTY=1

OUT="Desert/Common/Source/Common/Core/Version.gen.hpp"
NEW="// AUTO-GENERATED by scripts/GenVersion.sh — do not edit, do not commit.
#pragma once
#define DESERT_VERSION_BASE   \"${BASE}\"
#define DESERT_VERSION_COMMITS ${COUNT}u
#define DESERT_VERSION_HASH   \"${HASH}\"
#define DESERT_VERSION_BRANCH \"${BRANCH}\"
#define DESERT_VERSION_DIRTY  ${DIRTY}"

if [ ! -f "$OUT" ] || [ "$(cat "$OUT")" != "$NEW" ]; then
    printf '%s\n' "$NEW" > "$OUT"
    echo "--- Version: ${BASE}.${COUNT}+${HASH} (branch ${BRANCH}, dirty=${DIRTY})"
fi
